# Generated by Django 3.1.5 on 2021-01-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified', verbose_name='modified_at')),
                ('name', models.CharField(max_length=140, verbose_name='circle name')),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('about', models.CharField(max_length=155, verbose_name='circle desription')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='circles/pictures/')),
                ('rides_offered', models.PositiveIntegerField(default=0)),
                ('rides_taken', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='los circulos verificados son tomados como oficiales', verbose_name='verified_circle')),
                ('is_public', models.BooleanField(default=True, help_text='los circulos publicos no aparecen visibles para todo el publico')),
                ('is_limited', models.BooleanField(default=False, help_text='los cirulos limitados solo pueden atender una cierta cantidad de usuarios')),
                ('members_limit', models.PositiveIntegerField(default=0, help_text='numero de usuarios al que esta limitado el circulo')),
            ],
            options={
                'ordering': ['-rides_taken', '-rides_offered'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
